config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'static_pages#home'
  resources :beacons

  devise_for :users

  match '/home', to: 'static_pages#home', via: 'get'
  
  resources :users, only: [:index, :show]

end

app/models/beacon.rb
class Beacon < ActiveRecord::Base
  validates :major, :minor, :name, presence: true
  validates_inclusion_of :major, :minor, :in => 1..65535
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beacons_controller.rb
class BeaconsController < ApplicationController
  before_action :set_beacon, only: [:show, :edit, :update, :destroy]

  def index
    @beacons = Beacon.all
    if params[:major].nil? || params[:minor].nil?
      render json: @beacons
    else
      @beacon = Beacon.find_by(major: params[:major], minor: params[:minor])
      if @beacon.nil?
        render json: "No beacon found!", status: 404
      else
        render json: @beacon.to_json(:only => [:name, :description])
      end
    end
  end

  def show
    render json: @beacon
  end

  def new
    @beacon = Beacon.new
    respond_with(@beacon)
  end

  def edit
  end

  def create
    @beacon = Beacon.new(beacon_params)
    @beacon.save
    respond_with(@beacon)
  end

  def update
    @beacon.update(beacon_params)
    respond_with(@beacon)
  end

  def destroy
    @beacon.destroy
    respond_with(@beacon)
  end

  def find_beacon

  end

  private
    def set_beacon
      @beacon = Beacon.find(params[:id])
    end

    def beacon_params
      params.require(:beacon).permit(:UUID)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  	render json: @users
  end

  def show
  	@user = User.find(params[:id])
  	render json: @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beacons_helper.rb
module BeaconsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/beacons/_form.html.erb
<%= form_for(@beacon) do |f| %>
  <% if @beacon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beacon.errors.count, "error") %> prohibited this beacon from being saved:</h2>

      <ul>
      <% @beacon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %><br>
    <%= f.text_field :uuid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beacons/edit.html.erb
<h1>Editing beacon</h1>

<%= render 'form' %>

<%= link_to 'Show', @beacon %> |
<%= link_to 'Back', beacons_path %>

app/views/beacons/index.html.erb
<h1>Listing beacons</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beacons.each do |beacon| %>
      <tr>
        <td><%= beacon.uuid %></td>
        <td><%= beacon.description%></td>
        <td><%= link_to 'Show', beacon %></td>
        <td><%= link_to 'Edit', edit_beacon_path(beacon) %></td>
        <td><%= link_to 'Destroy', beacon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beacon', new_beacon_path %>

app/views/beacons/new.html.erb
<h1>New beacon</h1>

<%= render 'form' %>

<%= link_to 'Back', beacons_path %>

app/views/beacons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @beacon.uuid %>
</p>
<p>
  <strong>Description:</strong>
  <%= @beacon.description %>
</p>

<%= link_to 'Edit', edit_beacon_path(@beacon) %> |
<%= link_to 'Back', beacons_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ibeacon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
<%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "Sign in", new_user_session_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>